/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PretzelAgentsImport } from './routes/pretzelAgents'
import { Route as PretzelAgentImport } from './routes/pretzelAgent'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PretzelAgentsRoute = PretzelAgentsImport.update({
  id: '/pretzelAgents',
  path: '/pretzelAgents',
  getParentRoute: () => rootRoute,
} as any)

const PretzelAgentRoute = PretzelAgentImport.update({
  id: '/pretzelAgent',
  path: '/pretzelAgent',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pretzelAgent': {
      id: '/pretzelAgent'
      path: '/pretzelAgent'
      fullPath: '/pretzelAgent'
      preLoaderRoute: typeof PretzelAgentImport
      parentRoute: typeof rootRoute
    }
    '/pretzelAgents': {
      id: '/pretzelAgents'
      path: '/pretzelAgents'
      fullPath: '/pretzelAgents'
      preLoaderRoute: typeof PretzelAgentsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pretzelAgent': typeof PretzelAgentRoute
  '/pretzelAgents': typeof PretzelAgentsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pretzelAgent': typeof PretzelAgentRoute
  '/pretzelAgents': typeof PretzelAgentsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pretzelAgent': typeof PretzelAgentRoute
  '/pretzelAgents': typeof PretzelAgentsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pretzelAgent' | '/pretzelAgents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pretzelAgent' | '/pretzelAgents'
  id: '__root__' | '/' | '/pretzelAgent' | '/pretzelAgents'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PretzelAgentRoute: typeof PretzelAgentRoute
  PretzelAgentsRoute: typeof PretzelAgentsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PretzelAgentRoute: PretzelAgentRoute,
  PretzelAgentsRoute: PretzelAgentsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pretzelAgent",
        "/pretzelAgents"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pretzelAgent": {
      "filePath": "pretzelAgent.tsx"
    },
    "/pretzelAgents": {
      "filePath": "pretzelAgents.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
