/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PretzelsImport } from './routes/pretzels'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PretzelsRoute = PretzelsImport.update({
  id: '/pretzels',
  path: '/pretzels',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pretzels': {
      id: '/pretzels'
      path: '/pretzels'
      fullPath: '/pretzels'
      preLoaderRoute: typeof PretzelsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pretzels': typeof PretzelsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pretzels': typeof PretzelsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pretzels': typeof PretzelsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pretzels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pretzels'
  id: '__root__' | '/' | '/pretzels'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PretzelsRoute: typeof PretzelsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PretzelsRoute: PretzelsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pretzels"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pretzels": {
      "filePath": "pretzels.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
